### ISSUE TITLE
Language feature support for LLVM-based verifiers

### ISSUE THREAD

**Issue by alastairreid** [project-oak/rust-verification-tools#29]
This issue is to keep track of the status of Rust language/feature support.
It is limited to LLVM-based verifiers because MIR-based verifiers will probably have completely different issues.
Add new problems as they are discovered with links to more detailed issues if they exist

- [x] #[should_panic] support
- [x] #[test] support
- [x] Hybrid crates that include Rust + C code #6 
- [x] Crates that rely on C library calls #45
- [x] std.env.args #21
- [x] Thread support when only one thread is actually used #5 
- [ ] Thread support when multiple threads are used #5
- [ ] Floating point support (see #154 about KLEE)
- [ ] Dynamically linked Rust libraries #111
- [ ] Embedded assembly language (see [KLEE PR](https://github.com/klee/klee/pull/1404))
- [x] Processor specific SIMD intrinsics #44
- [ ] Processor specific non-SIMD intrinsics
